language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t maxim2andreev/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true maxim2andreev/react-test npm test

after_success:
  - docker build -t maxim2andreev/docker-study-complex-client ./client
  - docker build -t maxim2andreev/docker-study-complex-server ./server
  - docker build -t maxim2andreev/docker-study-complex-worker ./worker
  - docker build -t maxim2andreev/docker-study-complex-nginx ./nginx
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_LOGIN" --password-stdin 
  - docker push maxim2andreev/docker-study-complex-client
  - docker push maxim2andreev/docker-study-complex-server
  - docker push maxim2andreev/docker-study-complex-worker
  - docker push maxim2andreev/docker-study-complex-nginx

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "Multi-Container AWS"
  env: "Multicontaineraws-env"
  bucket_name: "elasticbeanstalk-eu-central-1-217003881490"
  bucket_path: "Multi-Container AWS"
  on:
      branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY